version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  app:
    build: .
    volumes:
      - ./data:/app/chroma_db
    environment:
      - CHROMA_PATH=/app/chroma_db
    depends_on:
      - ollama
    entrypoint: ["python", "app.py"]

volumes:
  ollama-data:
  data:
