services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:11434/api/version"]
      interval: 10s
      timeout: 2s
      retries: 10
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities: [gpu]

  web:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/app/chroma_db
      - ./uploads:/app/uploads
    environment:
      - CHROMA_PATH=/app/chroma_db
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"
volumes:
  ollama-data:
  data:
